# Generated by Django 6.0.2 on 2026-04-27 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание соперника'), ('playing', 'В процессе'), ('finished', 'Завершена'), ('aborted', 'Прервана')], default='waiting', max_length=10)),
                ('result', models.CharField(blank=True, choices=[('white_win', 'Победа белых'), ('black_win', 'Победа чёрных'), ('draw', 'Ничья')], max_length=10, null=True)),
                ('pgn', models.TextField(blank=True, help_text='PGN-запись партии')),
                ('current_fen', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')),
                ('time_control', models.PositiveIntegerField(default=600, help_text='Контроль времени в секундах')),
                ('is_deep_work', models.BooleanField(default=False, help_text='Партия сыграна в режиме Deep Work')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('black_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_white', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('san', models.CharField(help_text='Ход в SAN-нотации', max_length=10)),
                ('uci', models.CharField(help_text='UCI: e.g. e2e4', max_length=6)),
                ('fen_after', models.TextField()),
                ('move_number', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ход',
                'verbose_name_plural': 'Ходы',
                'ordering': ['move_number', 'created_at'],
            },
        ),
    ]
