# Generated by Django 6.0.3 on 2026-04-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('chess', 'Шахматы'), ('clothes', 'Одежда'), ('accessories', 'Аксессуары')], default='chess', max_length=16)),
                ('price', models.PositiveIntegerField(help_text='Цена в тенге')),
                ('image_url', models.URLField(blank=True, help_text='URL изображения (заглушка или CDN)')),
                ('is_active', models.BooleanField(default=True)),
                ('coming_soon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['category', 'price'],
            },
        ),
    ]
