# Generated by Django 6.0.3 on 2026-04-27 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lichess_id', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('fen', models.TextField(help_text='Начальная позиция FEN (ход соперника уже сделан)')),
                ('solution_moves', models.JSONField(help_text="Список ходов UCI: ['e2e4', 'd7d5']")),
                ('difficulty', models.CharField(choices=[('easy', 'Жеңіл'), ('medium', 'Орташа'), ('hard', 'Қиын')], default='medium', max_length=8)),
                ('themes', models.CharField(blank=True, help_text='Теги через пробел: fork pin mateIn2', max_length=255)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('rating', models.PositiveIntegerField(default=1500)),
                ('is_daily', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PuzzleSolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves_used', models.JSONField(help_text='Ходы, которые ввёл пользователь')),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='puzzles.puzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_solves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Решение задачи',
                'verbose_name_plural': 'Решения задач',
                'ordering': ['-solved_at'],
                'unique_together': {('user', 'puzzle')},
            },
        ),
    ]
