# Generated by Django 6.0.2 on 2026-04-27 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('nomad', 'Номад'), ('sarbaz', 'Сарбаз'), ('batyr', 'Батыр'), ('khan', 'Хан')], default='nomad', max_length=10)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveIntegerField(default=800)),
                ('asyqs', models.PositiveIntegerField(default=100, help_text='Баланс внутренней валюты «Асық»')),
                ('is_pro', models.BooleanField(default=False, help_text='Активна ли PRO-подписка «Focus Pass»')),
                ('pro_expires_at', models.DateTimeField(blank=True, help_text='Дата истечения подписки', null=True)),
                ('city', models.CharField(choices=[('almaty', 'Алматы'), ('astana', 'Астана'), ('shymkent', 'Шымкент'), ('karaganda', 'Қарағанды'), ('aktobe', 'Ақтөбе'), ('taraz', 'Тараз'), ('pavlodar', 'Павлодар'), ('ust_kamenogorsk', 'Өскемен'), ('semey', 'Семей'), ('atyrau', 'Атырау'), ('other', 'Басқа қала')], default='almaty', help_text='Город для городского лидерборда', max_length=30)),
                ('push_notifications_enabled', models.BooleanField(default=False, help_text='Браузерные push-уведомления о ходах соперника')),
                ('push_subscription_json', models.JSONField(blank=True, help_text='Web Push subscription объект от браузера', null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('games_drawn', models.PositiveIntegerField(default=0)),
                ('total_focus_minutes', models.PositiveIntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='AsyqTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asyq_transactions', to='users.profile')),
            ],
            options={
                'verbose_name': 'Транзакция асыков',
                'verbose_name_plural': 'Транзакции асыков',
                'ordering': ['-created_at'],
            },
        ),
    ]
